apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sentinel.io_sentinelservices.yaml
  - sentinel.io_slopolicies.yaml
  - sentinel.io_rolloutguards.yaml
  - sentinel.io_incidents.yaml
