apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - attesta.io_attestaservices.yaml
  - attesta.io_slopolicies.yaml
  - attesta.io_rolloutguards.yaml
  - attesta.io_incidents.yaml
